export { default as actions } from 'modules/comments/actions'
export { default as types } from 'modules/comments/types'
export { default as sagas } from 'modules/comments/sagas'
export * from 'modules/comments/selectors'
export { default as default } from 'modules/comments/reducers'
