export default {
  LOGIN_REQUEST: 'AUTH/LOGIN/REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN/SUCCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN/FAILURE',

  LOGOUT_REQUEST: 'AUTH/LOGOUT/REQUEST',
  LOGOUT_SUCCESS: 'AUTH/LOGOUT/SUCCESS',
  LOGOUT_FAILURE: 'AUTH/LOGOUT/FAILURE',

  REGISTER_REQUEST: 'AUTH/REGISTER/REQUEST',
  REGISTER_SUCCESS: 'AUTH/REGISTER/SUCCESS',
  REGISTER_FAILURE: 'AUTH/REGISTER/FAILURE',
}
