/** @module comments/types */

/**
 * Constants that represent the types of actions that are dispatched by comment
 * actions. 
 */
export default {
  FETCH_COMMENTS_FAILURE: 'COMMENTS/FETCH_FAILURE',
  FETCH_COMMENTS_REQUEST: 'COMMENTS/FETCH_REQUEST',

  CREATE_COMMENT_REQUEST: 'COMMENTS/CREATE_REQUEST',
  CREATE_COMMENT_SUCCESS: 'COMMENTS/CREATE_SUCCESS',
  CREATE_COMMENT_FAILURE: 'COMMENTS/CREATE_FAILURE',

  UPDATE_COMMENT_REQUEST: 'COMMENTS/UPDATE_REQUEST',
  UPDATE_COMMENT_SUCCESS: 'COMMENTS/UPDATE_SUCCESS',
  UPDATE_COMMENT_FAILURE: 'COMMENTS/UPDATE_FAILURE',

  DELETE_COMMENT_REQUEST: 'COMMENTS/DELETE_REQUEST',
  DELETE_COMMENT_SUCCESS: 'COMMENTS/DELETE_SUCCESS',
  DELETE_COMMENT_FAILURE: 'COMMENTS/DELETE_FAILURE',
}
