/** @module comments/types */

/**
 * Constants that represent the types of actions that are dispatched by comment
 * actions. 
 */
export default {
  FETCH_COMMENTS_FAILURE: 'PROJECTS/FETCH_FAILURE',
  FETCH_COMMENTS_REQUEST: 'PROJECTS/FETCH_REQUEST',

  CREATE_COMMENT_REQUEST: 'PROJECTS/CREATE_REQUEST',
  CREATE_COMMENT_SUCCESS: 'PROJECTS/CREATE_SUCCESS',
  CREATE_COMMENT_FAILURE: 'PROJECTS/CREATE_FAILURE',

  UPDATE_COMMENT_REQUEST: 'PROJECTS/UPDATE_REQUEST',
  UPDATE_COMMENT_SUCCESS: 'PROJECTS/UPDATE_SUCCESS',
  UPDATE_COMMENT_FAILURE: 'PROJECTS/UPDATE_FAILURE',

  DELETE_COMMENT_REQUEST: 'PROJECTS/DELETE_REQUEST',
  DELETE_COMMENT_SUCCESS: 'PROJECTS/DELETE_SUCCESS',
  DELETE_COMMENT_FAILURE: 'PROJECTS/DELETE_FAILURE',
}
