/** @module teams/types */

/**
 * Constants that represent the types of actions that are dispatched by team
 * actions.
 */
export default {
  FETCH_TEAMS_FAILURE: 'TEAMS/FETCH_FAILURE',
  FETCH_TEAMS_REQUEST: 'TEAMS/FETCH_REQUEST',

  CREATE_TEAM_REQUEST: 'TEAMS/CREATE_REQUEST',
  CREATE_TEAM_SUCCESS: 'TEAMS/CREATE_SUCCESS',
  CREATE_TEAM_FAILURE: 'TEAMS/CREATE_FAILURE',

  UPDATE_TEAM_REQUEST: 'TEAMS/UPDATE_REQUEST',
  UPDATE_TEAM_SUCCESS: 'TEAMS/UPDATE_SUCCESS',
  UPDATE_TEAM_FAILURE: 'TEAMS/UPDATE_FAILURE',

  DELETE_TEAM_REQUEST: 'TEAMS/DELETE_REQUEST',
  DELETE_TEAM_SUCCESS: 'TEAMS/DELETE_SUCCESS',
  DELETE_TEAM_FAILURE: 'TEAMS/DELETE_FAILURE',
}
