/** @module users/types */

/**
 * Constants that represent the types of actions that are dispatched by user
 * actions. 
 */
export default {
  FETCH_USERS_FAILURE: 'PROJECTS/FETCH_FAILURE',
  FETCH_USERS_REQUEST: 'PROJECTS/FETCH_REQUEST',

  CREATE_USER_REQUEST: 'PROJECTS/CREATE_REQUEST',
  CREATE_USER_SUCCESS: 'PROJECTS/CREATE_SUCCESS',
  CREATE_USER_FAILURE: 'PROJECTS/CREATE_FAILURE',

  UPDATE_USER_REQUEST: 'PROJECTS/UPDATE_REQUEST',
  UPDATE_USER_SUCCESS: 'PROJECTS/UPDATE_SUCCESS',
  UPDATE_USER_FAILURE: 'PROJECTS/UPDATE_FAILURE',

  DELETE_USER_REQUEST: 'PROJECTS/DELETE_REQUEST',
  DELETE_USER_SUCCESS: 'PROJECTS/DELETE_SUCCESS',
  DELETE_USER_FAILURE: 'PROJECTS/DELETE_FAILURE',
}
